logging:
  level:
    root: INFO
server:
  port: 8088
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    initialization-mode: never
    password: s3cretP@$$w0rd
    url: jdbc:mysql://localhost:3306/discovery_bank_schema?allowPublicKeyRetrieval=true&useSSL=false
    username: schemaManager
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  security:
    user:
      name: client
      password: password
